var teams = [
{
	"name" : "USA",
	"countryCode" : "us",
	"matches" : [
	{
		"opponent" : "Ghana",
		"round" : "Group G",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 8,
		"goalsAttemptedOnTarget" : 7,
		"possession" : 41,
		"shotsAllowed" : 1,
		"shotsAttempted" : 21,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Portugal",
		"round" : "Group G",
		"result" : "tie",
		"goalsScored" : 2,
		"goalsAttempted" : 15,
		"goalsAttemptedOnTarget" : 10,
		"possession" : 48,
		"shotsAllowed" : 2,
		"shotsAttempted" : 20,
		"shotsAttemptedOnTarget" : 9,
	},
	{
		"opponent" : "Germany",
		"round" : "Group G",
		"result" : "loss",
		"goalsScored" : 0,
		"goalsAttempted" : 4,
		"goalsAttemptedOnTarget" : 1,
		"possession" : 37,
		"shotsAllowed" : 1,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 9,
	},
	]
},
{
	"name" : "Belgium",
	"countryCode" : "be",
	"matches" : [
	{
		"opponent" : "Algeria",
		"round" : "Group H",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 16,
		"goalsAttemptedOnTarget" : 10,
		"possession" : 65,
		"shotsAllowed" : 1,
		"shotsAttempted" : 3,
		"shotsAttemptedOnTarget" : 1,
	},
	{
		"opponent" : "Russia",
		"round" : "Group H",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 11,
		"goalsAttemptedOnTarget" : 7,
		"possession" : 53,
		"shotsAllowed" : 0,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "Croatia",
		"round" : "Group A",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 16,
		"goalsAttemptedOnTarget" : 11,
		"possession" : 50,
		"shotsAllowed" : 0,
		"shotsAttempted" : 18,
		"shotsAttemptedOnTarget" : 12,
	},
	]
},
{
	"name" : "Brazil",
	"countryCode" : "br",
	"matches" : [
	{
		"opponent" : "Croatia",
		"round" : "Group A",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 14,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 58,
		"shotsAllowed" : 1,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 4,
	},
	{
		"opponent" : "Mexico",
		"round" : "Group A",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 14,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 54,
		"shotsAllowed" : 0,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 3,
	},
	{
		"opponent" : "Cameroon",
		"round" : "Group A",
		"result" : "win",
		"goalsScored" : 4,
		"goalsAttempted" : 19,
		"goalsAttemptedOnTarget" : 18,
		"possession" : 54,
		"shotsAllowed" : 1,
		"shotsAttempted" : 12,
		"shotsAttemptedOnTarget" : 6,
	},
	]
},
{
	"name" : "Chile",
	"countryCode" : "cl",
	"matches" : [
	{
		"opponent" : "Australia",
		"round" : "Group B",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 11,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 62,
		"shotsAllowed" : 1,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "Spain",
		"round" : "Group B",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 7,
		"goalsAttemptedOnTarget" : 4,
		"possession" : 44,
		"shotsAllowed" : 0,
		"shotsAttempted" : 15,
		"shotsAttemptedOnTarget" : 9,
	},
	{
		"opponent" : "Netherlands",
		"round" : "Group B",
		"result" : "loss",
		"goalsScored" : 0,
		"goalsAttempted" : 7,
		"goalsAttemptedOnTarget" : 1,
		"possession" : 64,
		"shotsAllowed" : 2,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 8,
	},
	]
},
{
	"name" : "Colombia",
	"countryCode" : "co",
	"matches" : [
	{
		"opponent" : "Greece",
		"round" : "Group C",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 12,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 46,
		"shotsAllowed" : 0,
		"shotsAttempted" : 12,
		"shotsAttemptedOnTarget" : 7,
	},
	{
		"opponent" : "Cote d'Ivoire",
		"round" : "Group C",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 11,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 45,
		"shotsAllowed" : 1,
		"shotsAttempted" : 15,
		"shotsAttemptedOnTarget" : 12,
	},
	{
		"opponent" : "Japan",
		"round" : "Group C",
		"result" : "win",
		"goalsScored" : 4,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 45,
		"shotsAllowed" : 1,
		"shotsAttempted" : 23,
		"shotsAttemptedOnTarget" : 13,
	},
	]
},
{
	"name" : "Uruguay",
	"countryCode" : "ur",
	"matches" : [
	{
		"opponent" : "Costa Rica",
		"round" : "Group D",
		"result" : "loss",
		"goalsScored" : 1,
		"goalsAttempted" : 9,
		"goalsAttemptedOnTarget" : 5,
		"possession" : 54,
		"shotsAllowed" : 3,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 4,
	},
	{
		"opponent" : "England",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 10,
		"goalsAttemptedOnTarget" : 6,
		"possession" : 38,
		"shotsAllowed" : 1,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Italy",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 14,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 45,
		"shotsAllowed" : 0,
		"shotsAttempted" : 9,
		"shotsAttemptedOnTarget" : 5,
	},
	]
},
{
	"name" : "Mexico",
	"countryCode" : "mx",
	"matches" : [
	{
		"opponent" : "Cameroon",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 9,
		"goalsAttemptedOnTarget" : 5,
		"possession" : 58,
		"shotsAllowed" : 0,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 4,
	},
	{
		"opponent" : "Brazil",
		"round" : "Group D",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 3,
		"possession" : 46,
		"shotsAllowed" : 0,
		"shotsAttempted" : 14,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Croatia",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 12,
		"goalsAttemptedOnTarget" : 7,
		"possession" : 45,
		"shotsAllowed" : 1,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 5,
	},
	]
},
{
	"name" : "Netherlands",
	"countryCode" : "nl",
	"matches" : [
	{
		"opponent" : "Spain",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 5,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 11,
		"possession" : 43,
		"shotsAllowed" : 1,
		"shotsAttempted" : 9,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "Australia",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 15,
		"goalsAttemptedOnTarget" : 14,
		"possession" : 52,
		"shotsAllowed" : 2,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Chile",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 36,
		"shotsAllowed" : 0,
		"shotsAttempted" : 7,
		"shotsAttemptedOnTarget" : 1,
	},
	]
},
{
	"name" : "Costa Rica",
	"countryCode" : "cr",
	"matches" : [
	{
		"opponent" : "Uruguay",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 12,
		"goalsAttemptedOnTarget" : 4,
		"possession" : 46,
		"shotsAllowed" : 1,
		"shotsAttempted" : 9,
		"shotsAttemptedOnTarget" : 5,
	},
	{
		"opponent" : "Italy",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 10,
		"goalsAttemptedOnTarget" : 6,
		"possession" : 42,
		"shotsAllowed" : 0,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "England",
		"round" : "Group D",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 4,
		"goalsAttemptedOnTarget" : 3,
		"possession" : 47,
		"shotsAllowed" : 0,
		"shotsAttempted" : 8,
		"shotsAttemptedOnTarget" : 3,
	},
	]
},
{
	"name" : "Greece",
	"countryCode" : "gr",
	"matches" : [
	{
		"opponent" : "Colombia",
		"round" : "Group D",
		"result" : "loss",
		"goalsScored" : 0,
		"goalsAttempted" : 12,
		"goalsAttemptedOnTarget" : 7,
		"possession" : 54,
		"shotsAllowed" : 3,
		"shotsAttempted" : 12,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Japan",
		"round" : "Group D",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 16,
		"goalsAttemptedOnTarget" : 11,
		"possession" : 68,
		"shotsAllowed" : 0,
		"shotsAttempted" : 9,
		"shotsAttemptedOnTarget" : 5,
	},
	{
		"opponent" : "Cote d'Ivoire",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 5,
		"possession" : 46,
		"shotsAllowed" : 1,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 9,
	},
	]
},
{
	"name" : "France",
	"countryCode" : "fr",
	"matches" : [
	{
		"opponent" : "Honduras",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 20,
		"goalsAttemptedOnTarget" : 10,
		"possession" : 63,
		"shotsAllowed" : 0,
		"shotsAttempted" : 4,
		"shotsAttemptedOnTarget" : 2,
	},
	{
		"opponent" : "Switzerland",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 5,
		"goalsAttempted" : 22,
		"goalsAttemptedOnTarget" : 16,
		"possession" : 43,
		"shotsAllowed" : 2,
		"shotsAttempted" : 17,
		"shotsAttemptedOnTarget" : 8,
	},
	{
		"opponent" : "Ecuador",
		"round" : "Group E",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 20,
		"goalsAttemptedOnTarget" : 13,
		"possession" : 60,
		"shotsAllowed" : 0,
		"shotsAttempted" : 11,
		"shotsAttemptedOnTarget" : 7,
	},
	]
},
{
	"name" : "Nigeria",
	"countryCode" : "ng",
	"matches" : [
	{
		"opponent" : "Iran",
		"round" : "Group D",
		"result" : "tie",
		"goalsScored" : 0,
		"goalsAttempted" : 10,
		"goalsAttemptedOnTarget" : 6,
		"possession" : 63,
		"shotsAllowed" : 0,
		"shotsAttempted" : 7,
		"shotsAttemptedOnTarget" : 3,
	},
	{
		"opponent" : "Bosnia & Herzegovina",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 20,
		"goalsAttemptedOnTarget" : 13,
		"possession" : 46,
		"shotsAllowed" : 0,
		"shotsAttempted" : 18,
		"shotsAttemptedOnTarget" : 10,
	},
	{
		"opponent" : "Argentina",
		"round" : "Group E",
		"result" : "loss",
		"goalsScored" : 2,
		"goalsAttempted" : 12,
		"goalsAttemptedOnTarget" : 7,
		"possession" : 43,
		"shotsAllowed" : 3,
		"shotsAttempted" : 18,
		"shotsAttemptedOnTarget" : 13,
	},
	]
},
{
	"name" : "Germany",
	"countryCode" : "de",
	"matches" : [
	{
		"opponent" : "Portugal",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 4,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 54,
		"shotsAllowed" : 0,
		"shotsAttempted" : 14,
		"shotsAttemptedOnTarget" : 9,
	},
	{
		"opponent" : "Ghana",
		"round" : "Group D",
		"result" : "tie",
		"goalsScored" : 2,
		"goalsAttempted" : 11,
		"goalsAttemptedOnTarget" : 6,
		"possession" : 59,
		"shotsAllowed" : 2,
		"shotsAttempted" : 20,
		"shotsAttemptedOnTarget" : 10,
	},
	{
		"opponent" : "USA",
		"round" : "Group E",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 13,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 63,
		"shotsAllowed" : 0,
		"shotsAttempted" : 4,
		"shotsAttemptedOnTarget" : 1,
	},
	]
},
{
	"name" : "Algeria",
	"countryCode" : "dz",
	"matches" : [
	{
		"opponent" : "Belgium",
		"round" : "Group D",
		"result" : "loss",
		"goalsScored" : 1,
		"goalsAttempted" : 3,
		"goalsAttemptedOnTarget" : 1,
		"possession" : 35,
		"shotsAllowed" : 2,
		"shotsAttempted" : 16,
		"shotsAttemptedOnTarget" : 10,
	},
	{
		"opponent" : "Korea Republic",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 4,
		"goalsAttempted" : 15,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 47,
		"shotsAllowed" : 2,
		"shotsAttempted" : 9,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "Russia",
		"round" : "Group E",
		"result" : "tie",
		"goalsScored" : 1,
		"goalsAttempted" : 8,
		"goalsAttemptedOnTarget" : 6,
		"possession" : 47,
		"shotsAllowed" : 1,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 7,
	},
	]
},
{
	"name" : "Argentina",
	"countryCode" : "ar",
	"matches" : [
	{
		"opponent" : "Bosnia & Herzegovina",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 11,
		"goalsAttemptedOnTarget" : 5,
		"possession" : 56,
		"shotsAllowed" : 1,
		"shotsAttempted" : 16,
		"shotsAttemptedOnTarget" : 11,
	},
	{
		"opponent" : "Iran",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 1,
		"goalsAttempted" : 19,
		"goalsAttemptedOnTarget" : 9,
		"possession" : 70,
		"shotsAllowed" : 0,
		"shotsAttempted" : 8,
		"shotsAttemptedOnTarget" : 4,
	},
	{
		"opponent" : "Nigeria",
		"round" : "Group E",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 18,
		"goalsAttemptedOnTarget" : 13,
		"possession" : 57,
		"shotsAllowed" : 2,
		"shotsAttempted" : 12,
		"shotsAttemptedOnTarget" : 7,
	},
	]
},
{
	"name" : "Switzerland",
	"countryCode" : "ch",
	"matches" : [
	{
		"opponent" : "Ecuador",
		"round" : "Group D",
		"result" : "win",
		"goalsScored" : 2,
		"goalsAttempted" : 18,
		"goalsAttemptedOnTarget" : 12,
		"possession" : 56,
		"shotsAllowed" : 1,
		"shotsAttempted" : 10,
		"shotsAttemptedOnTarget" : 6,
	},
	{
		"opponent" : "France",
		"round" : "Group D",
		"result" : "loss",
		"goalsScored" : 2,
		"goalsAttempted" : 17,
		"goalsAttemptedOnTarget" : 8,
		"possession" : 57,
		"shotsAllowed" : 5,
		"shotsAttempted" : 22,
		"shotsAttemptedOnTarget" : 16,
	},
	{
		"opponent" : "Honduras",
		"round" : "Group E",
		"result" : "win",
		"goalsScored" : 3,
		"goalsAttempted" : 16,
		"goalsAttemptedOnTarget" : 13,
		"possession" : 40,
		"shotsAllowed" : 0,
		"shotsAttempted" : 13,
		"shotsAttemptedOnTarget" : 6,
	},
	]
},
]
